@baseUrl = http://localhost:8080

### Create a game session
POST {{baseUrl}}/api/v1/game-sessions
Content-Type: application/json

{
  "boardId": "board-dummy-01"
}

> {%
    client.global.set("sessionId", response.body.data.gameSessionId);
%}

### Get the session (grab a clue id + confirm state)
GET {{baseUrl}}/api/v1/game-sessions/{{sessionId}}
Accept: application/json

> {%
    client.global.set("clueId", response.body.data.clues[0].id);
    client.test("session is in LOBBY", function() {
        client.assert(response.body.data.state === "LOBBY");
    });
%}

### Answer a clue
POST {{baseUrl}}/api/v1/game-sessions/{{sessionId}}/answer
Content-Type: application/json

{
  "clueId": "{{clueId}}",
  "answer": "A programming language"
}